name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代 码
        uses: actions/checkout@master
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ~/.ssh/deploy_key
          ARGS: "-avzr --delete"
          SOURCE: "./zero"
          REMOTE_HOST: "47.103.194.209"
          REMOTE_USER: "root"
          TARGET: "/root/test/"
