name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload dist directory to server
        run: scp -r zero Administrator@47.100.41.146:C:\dd\
