name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: -rltgoDzvO --delete
          SOURCE: zero/
          REMOTE_HOST: 47.103.194.209
          REMOTE_USER: Administrator
          TARGET: /root/test/
        
  