name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代 码
        uses: actions/checkout@master
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

       # 部署到服务器
      - name: deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的PRIVATE_KEY中
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          ARGS: "-avzr --delete" 
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          SOURCE: "./zero"
          # 服务器域名/IP
          REMOTE_HOST: "47.103.194.209"
          # 服务器默认用户名为root
          REMOTE_USER: "root"
          # 目标目录
          TARGET: "/root/test/"
