name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代 码
        uses: actions/checkout@master
      - name: Debug Private Key
        run: |
          cat /path/to/deploy.pem ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./zero"
          REMOTE_HOST: "47.103.194.209"
          REMOTE_USER: "root"
          TARGET: "/root/test/"
